### ISSUE TITLE
Camera permission is not checked when selecting the camera option to send a photo.

### ISSUE THREAD

**Issue by n2oghost** [parley-messaging/android-library#4]
This causes the camera option to not work and in the end I had to modify the sdk to check for permission in the openCamera method of the ComposeImageInputView.

**Comment by alexkok** [comment]
Thanks for the issue @n2oghost 

Will look into this and resolve it in in the next release. I'll let you know when the update is there.

**Comment by alexkok** [comment]
The Parley library doesn't require the camera permission to work. 

However: when the app declares usage of the `android.permission.CAMERA` permission inside the `AndroidManifest.xml`, Android requires Parley to check for this as well. This is fixed in #5.

@n2oghost please make sure to call `Parley.onRequestPermissionsResult(requestCode, permissions, grantResults)` from the activity inside the `onRequestPermissionsResult` method to have a smooth interaction when Parley requests permissions (check out Step 4 in the README).

**Comment by n2oghost** [comment]
Thank you for the quick fix and update! 👏

**Comment by alexkok** [comment]
No problem! Feel free to create another issue if you encounter issues when using Parley 👍
